name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
    
- type: dropdown
  id: os
  attributes:
    label: Which OS are you using?
    multiple: false
    options:
      - iOS
      - Android
  validations:
    required: true
    
- type: input
  attributes:
    label: OS Version
    placeholder: 16.3.1
    description: The version of iOS/iPad OS/Android running on your device.
  validations:
    required: true

- type: input
  attributes:
    label: Device
    placeholder: iPhone 14 Pro
    description: The model of your device.
  validations:
    required: true
    
- type: input
  attributes:
    label: App Version
    placeholder: 1.0.9
    description: The version of the app you are running, you can find it at the bottom of the settings screen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
