name: :star2: Feature request
description: Idea for a new feature
title: "[FEATURE] <title>"
labels: [feature request]
body:
- type: checkboxes
  attributes:
    label: Is there an existing feature request for this?
    description: Please search to see if an feature request already exists for the feature you are proposing.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Feature description
    description: A concise description of what the new feature should do.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the new feature!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
